### PR TITLE
Refactor and imporve

### PR DESCRIPTION
**Pull request by Vuurvos1**

### CODE REVIEW

**Review by RowinRuizendaal — APPROVED** [review]
LGTM

**Comment by Vuurvos1** [comment]
lol, not yet

**Comment by RowinRuizendaal** [comment]
Fuck you @Vuurvos1

**Comment by RowinRuizendaal** [comment]
Stinky stinky @Vuurvos1

**Comment by Vuurvos1** [comment]
Like this is ever going to get finished, lol

**Comment by RowinRuizendaal** [comment]
Idk 55 commits later, maybe this project can be finished after months lol

**Comment by Vuurvos1** [comment]
press x to doubt

**Comment by RowinRuizendaal** [comment]
press x to doubt

**Comment by Vuurvos1** [comment]
Let's deprecate this bad boy in favour of #52

**Pull request closed without merging**
